// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj_Iijxj4ZOU1d6nl9el2E0w95Dc3Scgg',
    appId: '1:788634630767:web:5697894f1e03fe9f25ab9a',
    messagingSenderId: '788634630767',
    projectId: 'diabete-app-12878',
    authDomain: 'diabete-app-12878.firebaseapp.com',
    storageBucket: 'diabete-app-12878.firebasestorage.app',
    measurementId: 'G-ES0EH1EMQP',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlrNUOuyqyO7nLm16UUqIEuCyhBI9VUGg',
    appId: '1:788634630767:ios:355f898e5e0cb10625ab9a',
    messagingSenderId: '788634630767',
    projectId: 'diabete-app-12878',
    storageBucket: 'diabete-app-12878.firebasestorage.app',
    iosBundleId: 'com.example.diabeteApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlrNUOuyqyO7nLm16UUqIEuCyhBI9VUGg',
    appId: '1:788634630767:ios:355f898e5e0cb10625ab9a',
    messagingSenderId: '788634630767',
    projectId: 'diabete-app-12878',
    storageBucket: 'diabete-app-12878.firebasestorage.app',
    iosBundleId: 'com.example.diabeteApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj_Iijxj4ZOU1d6nl9el2E0w95Dc3Scgg',
    appId: '1:788634630767:web:9b000273a76110b225ab9a',
    messagingSenderId: '788634630767',
    projectId: 'diabete-app-12878',
    authDomain: 'diabete-app-12878.firebaseapp.com',
    storageBucket: 'diabete-app-12878.firebasestorage.app',
    measurementId: 'G-QJTLP8V4YH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4zBu3o89XrJtdZZrNLkJCJGoogomGDHc',
    appId: '1:788634630767:android:141d69e62d975a5625ab9a',
    messagingSenderId: '788634630767',
    projectId: 'diabete-app-12878',
    storageBucket: 'diabete-app-12878.firebasestorage.app',
  );

}